<?php

namespace classes;

use Monolog\Handler\NoopHandler;
use Monolog\Logger;
use PHPUnit\Framework\TestCase;

class PDFConverterTest extends TestCase
{
    private $logger, $config;

    function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->logger = new Logger('test');
        $this->logger->pushHandler(new NoopHandler);

        $this->config = array();
    }

$expect = new PDFConverter($this->logger, $this->config);

}
