<?php

namespace classes;

use Monolog\Handler\NoopHandler;
use Monolog\Logger;
use PHPUnit\Framework\TestCase;
use protomuncher\classes\ConfigObject;
use protomuncher\classes\ConfigurationManager;

class PDFConverterTest extends TestCase
{
    private $logger, $config, $geraet, $database;

    function setUp() {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->logger = new Logger('test');
        $this->logger->pushHandler(new NoopHandler);

        $this->geraet = 1; // 1=MRT, 2=CT
        $this->config = new ConfigObject($this->geraet);

        $db = dirname(__DIR__) . '/conf/config.sqlite';
        $this->database = new Medoo([
            'database_type' => 'sqlite',
            'database_file' => $db
        ]);

        $configurationmanager = new ConfigurationManager($this->database, $this->config);
        $configurationmanager->populateConf();
    }

    public function testMriConvert() {
        $this->converter = new PDFConverter($this->logger, $this->config);
        $this->converter->set_modality('MRT');
        $this->converter->set_inut(dirname(__DIR__).'/test/fixtures/mrt_open.pdf');
        $result_array = $this->converter->convert();

        $this->assertIsArray($result_array);
        $this->assertArrayContainsKey('region', $result_array);
    }
}
