<?php
declare(strict_types=1);

namespace protomuncher\classes;

use Medoo\Medoo;
use Monolog\Handler\NoopHandler;
use Monolog\Logger;
use PHPUnit\Framework\TestCase;

class PDFConverterTest extends TestCase
{
    private $logger, $config, $geraet, $database;

    function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->logger = new Logger('test');
        $this->logger->pushHandler(new NoopHandler);

        $this->geraet = 1; // 1=MRT, 2=CT
        $this->config = new ConfigObject($this->geraet);

        $db = dirname(__DIR__) . '/../conf/config.sqlite';
        $this->database = new Medoo([
            'database_type' => 'sqlite',
            'database_file' => $db
        ]);

        $configurationmanager = new ConfigurationManager($this->database, $this->config);
        $configurationmanager->populateConf();
    }

    public function testMriConvert()
    {
        $this->converter = new PDFConverter($this->logger, $this->config);
        $this->converter->setmodality('MRT');
        $this->converter->setinput(dirname(__DIR__) . '/fixtures/mrt_open.pdf');
        $result_array = $this->converter->convert();

        $this->assertIsArray($result_array);
        $this->assertContains('region', $result_array, "Array doesn't contain 'region'");
    }
}
